language: c
env:
  global:
    # Setting this means rustc links properly
    - LD_LIBRARY_PATH: /usr/local/lib
before_install:
  # Downloading the nightly and installing manually works better than the PPA
  # for now.
  - curl -O http://static.rust-lang.org/dist/rust-nightly-x86_64-unknown-linux-gnu.tar.gz
  - tar xfz rust-nightly-x86_64-unknown-linux-gnu.tar.gz
  - (cd rust-nightly-x86_64-unknown-linux-gnu/ && sudo ./install.sh)
  # Cargo PPAs work great!
  - sudo add-apt-repository --yes ppa:cmrx64/cargo
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq cargo
script:
  # Test the cargo build
  - cargo build
  - cargo test
