language: c
install:
  - curl www.rust-lang.org/rustup.sh | sudo bash
script:
  - cargo build
  - cargo test
notifications:
  email:
    recipients:
      - franklinchen@franklinchen.com
    on_success: never
